name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    env:
      CC: gcc-11
      CXX: g++-11

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install GCC 11
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-11

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax

    - name: Install meson
      run: |
        python -m pip install --upgrade pip
        pip install meson

    - name: Install ninja
      run: sudo apt-get install ninja-build

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg --branch v3.0 --depth 1
        pushd zimg
        ./autogen.sh
        ./configure --disable-static --disable-simd
        make -j2
        sudo make install -j2
        popd
        rm -rf zimg

    - name: Install VapourSynth
      run: |
        git clone https://github.com/vapoursynth/vapoursynth --depth 1
        pushd vapoursynth
        ./autogen.sh
        ./configure --disable-static --disable-x86-asm --disable-vsscript --disable-vspipe --disable-python-module
        make -j2
        sudo make install -j2
        popd
        rm -rf vapoursynth

    - name: Install libvulkan-dev
      run: sudo apt-get install libvulkan-dev

    - name: Build
      run: |
        meson build
        ninja -C build

  macOS:
    runs-on: macos-latest

    env:
      CC: /usr/local/opt/llvm/bin/clang
      CXX: /usr/local/opt/llvm/bin/clang++

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install automake
      run: |
        brew update
        brew install automake

    - name: Install libomp
      run: brew install libomp

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax

    - name: Install meson
      run: |
        python -m pip install --upgrade pip
        pip install meson

    - name: Install ninja
      run: brew install ninja

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg --branch v3.0 --depth 1
        pushd zimg
        ./autogen.sh
        ./configure --disable-static --disable-simd
        make -j3
        sudo make install -j3
        popd
        rm -rf zimg

    - name: Install VapourSynth
      run: |
        git clone https://github.com/vapoursynth/vapoursynth --depth 1
        pushd vapoursynth
        ./autogen.sh
        ./configure --disable-static --disable-x86-asm --disable-vsscript --disable-vspipe --disable-python-module
        make -j3
        sudo make install -j3
        popd
        rm -rf vapoursynth

    - name: Cache Vulkan SDK
      id: cache-vulkansdk
      uses: actions/cache@v3
      with:
        path: vulkansdk-macos-1.2.170.0
        key: vulkansdk-macos-1.2.170.0

    - name: Install Vulkan SDK
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.2.170.0/mac/vulkansdk-macos-1.2.170.0.dmg
        hdiutil attach vulkansdk-macos-1.2.170.0.dmg
        cp -r /Volumes/vulkansdk-macos-1.2.170.0 .
        rm -rf vulkansdk-macos-1.2.170.0/Applications
        find vulkansdk-macos-1.2.170.0 -type f | grep -v -E 'vulkan|glslang|MoltenVK' | xargs rm
        hdiutil detach /Volumes/vulkansdk-macos-1.2.170.0

    - name: Set VULKAN_SDK
      run: echo "VULKAN_SDK=$GITHUB_WORKSPACE/vulkansdk-macos-1.2.170.0/macOS" >> $GITHUB_ENV

    - name: Build
      run: |
        meson build -Dcpp_args=-I$VULKAN_SDK/include -Dcpp_link_args=-L/usr/local/lib
        ninja -C build
